/**
 * Application-wide constants
 */

// Valid 400x400 white PNG image encoded as base64
// Used as a placeholder when no drawing is captured
export const BLANK_WHITE_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAIAAAAP3aGbAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH6AEGEjkKLQAAAAd0RVh0QXV0aG9yAKmuzEgAAAAMdEVYdERlc2NyaXB0aW9uABMJISMAAAAKdEVYdENvcHlyaWdodACsD8w6AAAADnRFWHRDcmVhdGlvbiB0aW1lADX3DwkAAAAJdEVYdFNvZnR3YXJlAF1w/zoAAAALdEVYdERpc2NsYWltZXIAt8C0jwAAAAh0RVh0V2FybmluZwDAG+aHAAAAB3RFWHRTb3VyY2UA9f+D6wAAAAh0RVh0Q29tbWVudAD2zJa/AAAABnRFWHRUaXRsZQCo7tInAAACEklEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA3wMehQABLq9o0QAAAABJRU5ErkJggg==';

// Minimum valid base64 length to consider a drawing "real"
// Anything shorter is likely an error or empty capture
export const MIN_VALID_DRAWING_LENGTH = 100;

// Timer colors for drawing screen
export const TIMER_COLORS = {
  CRITICAL: '#e74c3c', // Red - 10 seconds or less
  WARNING: '#e67e22', // Orange - 30 seconds or less
};

// Room cleanup configuration
export const CLEANUP_CONFIG = {
  FINISHED_ROOM_MAX_AGE_MS: 1 * 60 * 60 * 1000, // 1 hour for finished games
  STALE_ROOM_MAX_AGE_MS: 24 * 60 * 60 * 1000, // 24 hours for any room
  ARCHIVE_MAX_AGE_DAYS: 30,
};

// Canvas capture configuration
export const CANVAS_CAPTURE = {
  INTERVAL_MS: 5000, // How often to capture canvas for backup (increased to reduce stutter)
  FORMAT: 'png',
  QUALITY: 0.8, // Slightly lower quality for faster capture
};

// Drawing tool configuration
export const DRAWING_CONFIG = {
  PEN_STROKE_WIDTH: 4,
  ERASER_STROKE_WIDTH: 24,
};

// Multiplayer configuration
export const MULTIPLAYER_CONFIG = {
  MAX_PLAYERS: 8,
  // After the drawing timer expires, wait this long for stragglers before
  // any client may force-advance the round (covers disconnected players)
  ROUND_ADVANCE_GRACE_MS: 15000,
};
